<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_right_click</name>
   <tag></tag>
   <elementGuidId>6d932cda-7984-403d-87b2-b1aeef21d54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rightClickMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rightClickMessage&quot;]</value>
      <webElementGuid>acb2dc4f-b894-49db-9591-dcdd46c52b07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
